used string value of step outcome

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -21,7 +21,12 @@ jobs:
       - name: print linting outcome
         if: '!cancelled()'
         run: |
-          result=${{ steps.lint.outcome }} == "success"
-          echo $result
+          if [ "${{ steps.lint.outcome }}" = "success" ]; then
+            echo "linting successful."
+            exit 0
+          else
+            echo "linting failed."
+            exit 1
+          fi
           
           
